### ISSUE TITLE
Adding a close icon

### ISSUE THREAD

**Issue by FarazPatankar** [Cogoport/cogo-toast#69]
Is there a recommended solution to adding a close icon to the toast? Based on what I can see in docs, we can have the toast close by simply clicking on it but how do my users know that if they don't see a close icon?

I also noticed we can pass JSX to the toast itself. Is that what we're expected to do in such a situation or is there a better alternative?

**Comment by aviral-clarifai** [comment]
If the JSX solution works for you; you can easily make your own helper over cogotoast that reads 'showClose' prop and renders whatever you give it with a predefined close icon. that's the best way to do it. you could alias it in your webpack build to something like `appUtils/toast' or 'toast' to as to use `import toast from 'appUtils/toast';` instead of doing `import cogoToast from 'cogo-toast';`

**Comment by mirshko** [comment]
I actually wrote a custom toast hook ontop of it,

```js
export const addToast = ({ body, type = "success", hideAfter = 6 }) => {
  const { hide } = cogoToast[type](
    <ToastBody body={body} onDismiss={() => hide()} />,
    {
      renderIcon: TOAST_ICONS[type],
      position: "bottom-right",
      hideAfter,
      bar: {
        size: "1px",
        style: "solid",
        color: "#f3f4f7",
      },
    }
  );

  return { hide };
};
```

`<ToastBody ... />` is just a JSX component that has a button and some other markup for handling the body, and `TOAST_ICONS` are just my custom JSX / SVG icons.

**Comment by aviral-clarifai** [comment]
@mirshko great solution! 
@faraz you could probably close this issue; this library already supports that feature in your own way without tying you to their implementation limits.

**Comment by ssngurjar** [comment]
@FarazPatankar you can use JSX solution as suggested by  @aviral-clarifai. You can use JSX for handling the markup body. Closing the issue as it can be solved using JSX
